### ISSUE TITLE
Does this package work with armv7l?

### ISSUE THREAD

**Issue by josegonzalez** [robxu9/bash-static#20]
I'd like to build a version of `dokku/plugn` - which uses this library - with raspberry pi support. I believe that means 32-bit for armv7l, but its not clear to me if the release is 32 or 64 bit.

Also, do we have an armv8 release?

**Comment by robxu9** [comment]
I've built an arm64 version of bash for macOS with the latest bash release, though I'm having some trouble combining them into a universal binary - I suspect most likely because I am not compiling them with XCode's clang, but with gcc instead. Regardless, I haven't tested it because I don't have a M1, but let me know if it works if you can!

**Comment by josegonzalez** [comment]
Seems to work!
